trigger:
  branches:
    include:
      - "*"

pr:
  branches:
    include:
      - "*"

stages:
  - stage: WidgetbookHostingStage
    displayName: Hosting
    jobs:
      - job: HostingJob
        displayName: Hosting
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: FlutterInstall@0
            displayName: "Install Flutter SDK"
            inputs:
              mode: "auto"
              channel: "stable"
              version: "latest"

          - task: Bash@3
            displayName: "Bootstrap App"
            inputs:
              targetType: "inline"
              script: |
                $(FlutterToolPath)/flutter pub get
                $(FlutterToolPath)/flutter gen-l10n

          - task: Bash@3
            displayName: "Build Widgetbook"
            inputs:
              workingDirectory: "widgetbook"
              targetType: "inline"
              script: |
                $(FlutterToolPath)/flutter pub get
                $(DartToolPath)/dart run build_runner build -d
                $(FlutterToolPath)/flutter build web -t lib/main.dart

          - task: Bash@3
            displayName: "Install Widgetbook CLI"
            inputs:
              targetType: "inline"
              script: |
                $(DartToolPath)/dart pub global activate widgetbook_cli

          - task: Bash@3
            displayName: "Push Widgetbook Build (Staging)"
            inputs:
              workingDirectory: "widgetbook"
              targetType: "inline"
              script: |
                $HOME/.pub-cache/bin/widgetbook_staging cloud build push --api-key $(WIDGETBOOK_STAGING_API_KEY)

          - task: Bash@3
            displayName: "Push Widgetbook Build (Production)"
            inputs:
              workingDirectory: "widgetbook"
              targetType: "inline"
              script: |
                $HOME/.pub-cache/bin/widgetbook cloud build push --api-key $(WIDGETBOOK_API_KEY)
