trigger:
  branches:
    include:
    - '*'

stages:
- stage: WidgetbookHostingStage
  dependsOn: []
  displayName: Hosting
  jobs:

  - job: HostingJob
    pool:
      vmImage: 'ubuntu-latest'
    displayName: Hosting
    steps:

    - task: FlutterInstall@0
      displayName: "Install Flutter SDK"
      inputs:
        mode: 'auto'
        channel: 'stable'
        version: 'latest'

    - task: Bash@3
      displayName: "Run build_runner"
      inputs:
        targetType: 'inline'
        script: |
          $(FlutterToolPath)/flutter pub get 
          $(FlutterToolPath)/flutter pub run build_runner build --delete-conflicting-outputs

    - task: Bash@3
      displayName: "Build Widgetbook"
      inputs:
        targetType: 'inline'
        script: |
          $(FlutterToolPath)/flutter build web -t lib/widgetbook.dart

    - task: Bash@3
      displayName: "Activate Widgetbook CLI"
      inputs:
        targetType: 'inline'
        script: |
          $(FlutterToolPath)/flutter pub global activate widgetbook_cli 

    - task: Bash@3
      displayName: "Upload Widgetbook"
      inputs:
        targetType: 'inline'
        script: |
          export PATH="/bin/:/usr/bin:$(FlutterToolPath):$(FlutterPubCachePath)"
          widgetbook publish \
              --api-key 7396fbb0851ab29f0cc78246355b786de54a087dba3828acde90ac7afef7d97f \
              --branch '$(Build.SourceBranch)' \
              --repository '$(Build.DefinitionName)' \
              --commit '$(Build.SourceVersion)' \
              --actor '$(Build.SourceVersionAuthor)'