name: Deploy Demo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # Only run it if the service account is set,
    # to avoid running it on internal forks (e.g. e2e)
    if: ${{ secrets.STORAGE_SERVICE_ACCOUNT != '' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Bootstrap
        uses: ./.github/actions/bootstrap

      - name: Authenticate Service Account
        uses: google-github-actions/auth@v1.0.0
        with:
          credentials_json: ${{ secrets.STORAGE_SERVICE_ACCOUNT }}

      - name: Deploy to demo.widgetbook.io
        uses: google-github-actions/upload-cloud-storage@v1.0.0
        with:
          path: widgetbook/build/web
          destination: demo.widgetbook.io
          parent: false
