name: Upload Widgetbook Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build App
        run: |
          flutter pub get
          flutter gen-l10n

      - name: Install Widgetbook CLI
        run: dart pub global activate widgetbook_cli

      - name: Build Widgetbook
        working-directory: widgetbook
        run: |
          flutter pub get
          dart run build_runner build -d
          flutter build web -t lib/main.dart

      - name: Upload Widgetbook
        working-directory: widgetbook
        run: widgetbook publish --api-key ${{ secrets.WIDGETBOOK_CLOUD_API_KEY }}

      - name: Authenticate Service Account
        uses: google-github-actions/auth@v1.0.0
        with:
          credentials_json: ${{ secrets.STORAGE_SERVICE_ACCOUNT }}

      - name: Deploy to demo.widgetbook.io
        uses: google-github-actions/upload-cloud-storage@v1.0.0
        with:
          path: widgetbook/build/web
          destination: demo.widgetbook.io
          parent: false
